CREATE OR REPLACE VIEW DEVV_STG_FLX.STTB_VALUE_DESC_get_delta AS LOCKING ROW FOR ACCESS
SELECT
  COALESCE(X.BLOCK_NAME, Y.BLOCK_NAME) AS BLOCK_NAME,
  COALESCE(X.FUNCTION_ID, Y.FUNCTION_ID) AS FUNCTION_ID,
  COALESCE(X.ITEM_NAME, Y.ITEM_NAME) AS ITEM_NAME,
  COALESCE(X.ITEM_VALUE, Y.ITEM_VALUE) AS ITEM_VALUE,
  COALESCE(X.LANGUAGE_CODE, Y.LANGUAGE_CODE) AS LANGUAGE_CODE,
  X.BM_ITEM_VALUE,
  X.ITEM_VAL_DESC,
  COALESCE(X.ETL_START_DT, Y.ETL_START_DT) AS ETL_START_DT, /* -----NO_CHANGE----------- */
  X.ETL_END_DT,
  X.RECORD_DELETED_FLAG,
  X.PROCESS_NAME,
  X.UPDATE_PROCESS_NAME,
  X.EXT_SS_ID,
  X.EXE_PROCESS_ID,
  X.UPDATE_PROCESS_ID,
  COALESCE(X.ETL_START_TS, Y.ETL_START_TS) AS ETL_START_TS,
  X.ETL_END_TS,
  CASE
    WHEN Y.BLOCK_NAME IS NULL
    AND Y.FUNCTION_ID IS NULL
    AND Y.ITEM_NAME IS NULL
    AND Y.ITEM_VALUE IS NULL
    AND Y.LANGUAGE_CODE IS NULL
    THEN 'INS' /* - IF MULTIPLE PKs are there then concatenate them with AND */
    WHEN X.BLOCK_NAME = Y.BLOCK_NAME
    AND X.FUNCTION_ID = Y.FUNCTION_ID
    AND X.ITEM_NAME = Y.ITEM_NAME
    AND X.ITEM_VALUE = Y.ITEM_VALUE
    AND X.LANGUAGE_CODE = Y.LANGUAGE_CODE /* - IF MULTIPLE PKs are there then concatenate them with AND */
    AND (
      (
        (
          X.BM_ITEM_VALUE IS NULL AND NOT Y.BM_ITEM_VALUE IS NULL
        )
        OR (
          NOT X.BM_ITEM_VALUE IS NULL AND Y.BM_ITEM_VALUE IS NULL
        )
        OR (
          X.BM_ITEM_VALUE <> Y.BM_ITEM_VALUE
        )
      )
      OR (
        (
          X.ITEM_VAL_DESC IS NULL AND NOT Y.ITEM_VAL_DESC IS NULL
        )
        OR (
          NOT X.ITEM_VAL_DESC IS NULL AND Y.ITEM_VAL_DESC IS NULL
        )
        OR (
          X.ITEM_VAL_DESC <> Y.ITEM_VAL_DESC
        )
      )
    )
    THEN 'UPD'
    WHEN X.BLOCK_NAME IS NULL
    AND X.FUNCTION_ID IS NULL
    AND X.ITEM_NAME IS NULL
    AND X.ITEM_VALUE IS NULL
    AND X.LANGUAGE_CODE IS NULL
    THEN 'DEL' /* - IF MULTIPLE PKs are there then concatenate them with AND */
  END AS OPT_FLAG
FROM DEVT_STG_FLX.STTB_VALUE_DESC AS X
FULL JOIN DEVT_STG_FLX.STTB_VALUE_DESC_BACKUP AS Y
  ON X.BLOCK_NAME = Y.BLOCK_NAME
  AND X.FUNCTION_ID = Y.FUNCTION_ID
  AND X.ITEM_NAME = Y.ITEM_NAME
  AND X.ITEM_VALUE = Y.ITEM_VALUE
  AND X.LANGUAGE_CODE = Y.LANGUAGE_CODE /* - IF MULTIPLE PKs are there then concatenate them with AND */
WHERE
  NOT OPT_FLAG IS NULL