
  REPLACE VIEW DEVV_STG_FLX.STTM_CUST_DOMESTIC AS
  LOCK ROW FOR ACCESS
  SELECT
  COALESCE(X.CUSTOMER_NO, Y.CUSTOMER_NO) AS CUSTOMER_NO,
  X.ACCOMODATION, X.BM_EDUCATIONAL_STATUS, X.BM_MARITAL_STATUS, X.DEPENDENT_CHILDREN, X.DEPENDENT_OTHERS, X.EDUCATIONAL_STATUS, X.MARITAL_STATUS, X.MOTHER_MAIDEN_NAME, X.SK_CUSTOMER_NO, X.SPOUSE_EMP_STATUS, X.SPOUSE_NAME,
  -------NO_CHANGE-----------
  COALESCE(X.ETL_START_DT,Y.ETL_START_DT) AS ETL_START_DT,
  X.ETL_END_DT,
  X.RECORD_DELETED_FLAG,
  X.PROCESS_NAME,
  X.UPDATE_PROCESS_NAME,
  X.EXT_SS_ID,
  X.EXE_PROCESS_ID,
  X.UPDATE_PROCESS_ID,
  COALESCE(X.ETL_START_TS,Y.ETL_START_TS) AS ETL_START_TS,
  X.ETL_END_TS,
  CASE WHEN Y.CUSTOMER_NO IS NULL THEN 'INS' --- IF MULTIPLE PKs are there then concatenate them with AND
  WHEN X.CUSTOMER_NO = Y.CUSTOMER_NO  --- IF MULTIPLE PKs are there then concatenate them with AND
  AND(
  ( (X.ACCOMODATION IS NULL AND Y.ACCOMODATION IS NOT NULL) OR (X.ACCOMODATION IS NOT NULL AND Y.ACCOMODATION IS NULL) OR (X.ACCOMODATION <> Y.ACCOMODATION)) OR (X.BM_EDUCATIONAL_STATUS IS NULL AND Y.BM_EDUCATIONAL_STATUS IS NOT NULL) OR (X.BM_EDUCATIONAL_STATUS IS NOT NULL AND Y.BM_EDUCATIONAL_STATUS IS NULL) OR (X.BM_EDUCATIONAL_STATUS <> Y.BM_EDUCATIONAL_STATUS)) OR (X.BM_MARITAL_STATUS IS NULL AND Y.BM_MARITAL_STATUS IS NOT NULL) OR (X.BM_MARITAL_STATUS IS NOT NULL AND Y.BM_MARITAL_STATUS IS NULL) OR (X.BM_MARITAL_STATUS <> Y.BM_MARITAL_STATUS)) OR (X.DEPENDENT_CHILDREN IS NULL AND Y.DEPENDENT_CHILDREN IS NOT NULL) OR (X.DEPENDENT_CHILDREN IS NOT NULL AND Y.DEPENDENT_CHILDREN IS NULL) OR (X.DEPENDENT_CHILDREN <> Y.DEPENDENT_CHILDREN)) OR (X.DEPENDENT_OTHERS IS NULL AND Y.DEPENDENT_OTHERS IS NOT NULL) OR (X.DEPENDENT_OTHERS IS NOT NULL AND Y.DEPENDENT_OTHERS IS NULL) OR (X.DEPENDENT_OTHERS <> Y.DEPENDENT_OTHERS)) OR (X.EDUCATIONAL_STATUS IS NULL AND Y.EDUCATIONAL_STATUS IS NOT NULL) OR (X.EDUCATIONAL_STATUS IS NOT NULL AND Y.EDUCATIONAL_STATUS IS NULL) OR (X.EDUCATIONAL_STATUS <> Y.EDUCATIONAL_STATUS)) OR (X.MARITAL_STATUS IS NULL AND Y.MARITAL_STATUS IS NOT NULL) OR (X.MARITAL_STATUS IS NOT NULL AND Y.MARITAL_STATUS IS NULL) OR (X.MARITAL_STATUS <> Y.MARITAL_STATUS)) OR (X.MOTHER_MAIDEN_NAME IS NULL AND Y.MOTHER_MAIDEN_NAME IS NOT NULL) OR (X.MOTHER_MAIDEN_NAME IS NOT NULL AND Y.MOTHER_MAIDEN_NAME IS NULL) OR (X.MOTHER_MAIDEN_NAME <> Y.MOTHER_MAIDEN_NAME)) OR (X.SK_CUSTOMER_NO IS NULL AND Y.SK_CUSTOMER_NO IS NOT NULL) OR (X.SK_CUSTOMER_NO IS NOT NULL AND Y.SK_CUSTOMER_NO IS NULL) OR (X.SK_CUSTOMER_NO <> Y.SK_CUSTOMER_NO)) OR (X.SPOUSE_EMP_STATUS IS NULL AND Y.SPOUSE_EMP_STATUS IS NOT NULL) OR (X.SPOUSE_EMP_STATUS IS NOT NULL AND Y.SPOUSE_EMP_STATUS IS NULL) OR (X.SPOUSE_EMP_STATUS <> Y.SPOUSE_EMP_STATUS)) OR (X.SPOUSE_NAME IS NULL AND Y.SPOUSE_NAME IS NOT NULL) OR (X.SPOUSE_NAME IS NOT NULL AND Y.SPOUSE_NAME IS NULL) OR (X.SPOUSE_NAME <> Y.SPOUSE_NAME)) ) THEN 'UPD'
  WHEN X.CUSTOMER_NO IS NULL THEN 'DEL' --- IF MULTIPLE PKs are there then concatenate them with AND
  END AS OPT_FLAG
  FROM DEVT_STG_FLX.STTM_CUST_DOMESTIC X
  FULL JOIN DEVT_STG_FLX.STTM_CUST_DOMESTIC_BACKUP Y
  ON X.CUSTOMER_NO = Y.CUSTOMER_NO --- IF MULTIPLE PKs are there then concatenate them with AND
  WHERE OPT_FLAG IS NOT NULL;
 