
  REPLACE VIEW DEVV_STG_FLX.STTM_DATES AS
  LOCK ROW FOR ACCESS
  SELECT
  COALESCE(X.BRANCH_CODE, Y.BRANCH_CODE) AS BRANCH_CODE,
  X.AUTH_STAT, X.CHECKER_DT_STAMP, X.CHECKER_ID, X.MAKER_DT_STAMP, X.MAKER_ID, X.MOD_NO, X.NEXT_WORKING_DAY, X.ONCE_AUTH, X.PREV_WORKING_DAY, X.RECORD_STAT, X.TODAY,
  -------NO_CHANGE-----------
  COALESCE(X.ETL_START_DT,Y.ETL_START_DT) AS ETL_START_DT,
  X.ETL_END_DT,
  X.RECORD_DELETED_FLAG,
  X.PROCESS_NAME,
  X.UPDATE_PROCESS_NAME,
  X.EXT_SS_ID,
  X.EXE_PROCESS_ID,
  X.UPDATE_PROCESS_ID,
  COALESCE(X.ETL_START_TS,Y.ETL_START_TS) AS ETL_START_TS,
  X.ETL_END_TS,
  CASE WHEN Y.BRANCH_CODE IS NULL THEN 'INS' --- IF MULTIPLE PKs are there then concatenate them with AND
  WHEN X.BRANCH_CODE = Y.BRANCH_CODE  --- IF MULTIPLE PKs are there then concatenate them with AND
  AND(
  ( (X.AUTH_STAT IS NULL AND Y.AUTH_STAT IS NOT NULL) OR (X.AUTH_STAT IS NOT NULL AND Y.AUTH_STAT IS NULL) OR (X.AUTH_STAT <> Y.AUTH_STAT)) OR (X.CHECKER_DT_STAMP IS NULL AND Y.CHECKER_DT_STAMP IS NOT NULL) OR (X.CHECKER_DT_STAMP IS NOT NULL AND Y.CHECKER_DT_STAMP IS NULL) OR (X.CHECKER_DT_STAMP <> Y.CHECKER_DT_STAMP)) OR (X.CHECKER_ID IS NULL AND Y.CHECKER_ID IS NOT NULL) OR (X.CHECKER_ID IS NOT NULL AND Y.CHECKER_ID IS NULL) OR (X.CHECKER_ID <> Y.CHECKER_ID)) OR (X.MAKER_DT_STAMP IS NULL AND Y.MAKER_DT_STAMP IS NOT NULL) OR (X.MAKER_DT_STAMP IS NOT NULL AND Y.MAKER_DT_STAMP IS NULL) OR (X.MAKER_DT_STAMP <> Y.MAKER_DT_STAMP)) OR (X.MAKER_ID IS NULL AND Y.MAKER_ID IS NOT NULL) OR (X.MAKER_ID IS NOT NULL AND Y.MAKER_ID IS NULL) OR (X.MAKER_ID <> Y.MAKER_ID)) OR (X.MOD_NO IS NULL AND Y.MOD_NO IS NOT NULL) OR (X.MOD_NO IS NOT NULL AND Y.MOD_NO IS NULL) OR (X.MOD_NO <> Y.MOD_NO)) OR (X.NEXT_WORKING_DAY IS NULL AND Y.NEXT_WORKING_DAY IS NOT NULL) OR (X.NEXT_WORKING_DAY IS NOT NULL AND Y.NEXT_WORKING_DAY IS NULL) OR (X.NEXT_WORKING_DAY <> Y.NEXT_WORKING_DAY)) OR (X.ONCE_AUTH IS NULL AND Y.ONCE_AUTH IS NOT NULL) OR (X.ONCE_AUTH IS NOT NULL AND Y.ONCE_AUTH IS NULL) OR (X.ONCE_AUTH <> Y.ONCE_AUTH)) OR (X.PREV_WORKING_DAY IS NULL AND Y.PREV_WORKING_DAY IS NOT NULL) OR (X.PREV_WORKING_DAY IS NOT NULL AND Y.PREV_WORKING_DAY IS NULL) OR (X.PREV_WORKING_DAY <> Y.PREV_WORKING_DAY)) OR (X.RECORD_STAT IS NULL AND Y.RECORD_STAT IS NOT NULL) OR (X.RECORD_STAT IS NOT NULL AND Y.RECORD_STAT IS NULL) OR (X.RECORD_STAT <> Y.RECORD_STAT)) OR (X.TODAY IS NULL AND Y.TODAY IS NOT NULL) OR (X.TODAY IS NOT NULL AND Y.TODAY IS NULL) OR (X.TODAY <> Y.TODAY)) ) THEN 'UPD'
  WHEN X.BRANCH_CODE IS NULL THEN 'DEL' --- IF MULTIPLE PKs are there then concatenate them with AND
  END AS OPT_FLAG
  FROM DEVT_STG_FLX.STTM_DATES X
  FULL JOIN DEVT_STG_FLX.STTM_DATES_BACKUP Y
  ON X.BRANCH_CODE = Y.BRANCH_CODE --- IF MULTIPLE PKs are there then concatenate them with AND
  WHERE OPT_FLAG IS NOT NULL;
 