CREATE OR REPLACE VIEW DEVV_STG_FLX.VIEW_CONTRACT_UDF_get_delta AS LOCKING ROW FOR ACCESS
SELECT
  COALESCE(X.CONTRACT_REF_NO, Y.CONTRACT_REF_NO) AS CONTRACT_REF_NO,
  COALESCE(X.VERSION_NO, Y.VERSION_NO) AS VERSION_NO,
  X.BM_FIELD_VAL_ATTORNEY,
  X.BM_LOV_SME_CUST_NATIONALITY,
  X.BM_LOV_SME_MAKER_DEPARTMENT,
  X.SK_CONTRACT_REF_NO,
  X.SK_FIELD_VAL_AUDI_CUST,
  X.SK_FIELD_VAL_DEPOSITOR,
  X.SK_PRODUCT_CODE,
  X.SK_FIELD_VAL_WALKING_CUST,
  COALESCE(X.ETL_START_DT, Y.ETL_START_DT) AS ETL_START_DT, /* -----NO_CHANGE----------- */
  X.ETL_END_DT,
  X.RECORD_DELETED_FLAG,
  X.PROCESS_NAME,
  X.UPDATE_PROCESS_NAME,
  X.EXT_SS_ID,
  X.EXE_PROCESS_ID,
  X.UPDATE_PROCESS_ID,
  COALESCE(X.ETL_START_TS, Y.ETL_START_TS) AS ETL_START_TS,
  X.ETL_END_TS,
  CASE
    WHEN Y.CONTRACT_REF_NO IS NULL AND Y.VERSION_NO IS NULL
    THEN 'INS' /* - IF MULTIPLE PKs are there then concatenate them with AND */
    WHEN X.CONTRACT_REF_NO = Y.CONTRACT_REF_NO
    AND X.VERSION_NO = Y.VERSION_NO /* - IF MULTIPLE PKs are there then concatenate them with AND */
    AND (
      (
        (
          X.BM_FIELD_VAL_ATTORNEY IS NULL AND NOT Y.BM_FIELD_VAL_ATTORNEY IS NULL
        )
        OR (
          NOT X.BM_FIELD_VAL_ATTORNEY IS NULL AND Y.BM_FIELD_VAL_ATTORNEY IS NULL
        )
        OR (
          X.BM_FIELD_VAL_ATTORNEY <> Y.BM_FIELD_VAL_ATTORNEY
        )
      )
      OR (
        (
          X.BM_LOV_SME_CUST_NATIONALITY IS NULL
          AND NOT Y.BM_LOV_SME_CUST_NATIONALITY IS NULL
        )
        OR (
          NOT X.BM_LOV_SME_CUST_NATIONALITY IS NULL
          AND Y.BM_LOV_SME_CUST_NATIONALITY IS NULL
        )
        OR (
          X.BM_LOV_SME_CUST_NATIONALITY <> Y.BM_LOV_SME_CUST_NATIONALITY
        )
      )
      OR (
        (
          X.BM_LOV_SME_MAKER_DEPARTMENT IS NULL
          AND NOT Y.BM_LOV_SME_MAKER_DEPARTMENT IS NULL
        )
        OR (
          NOT X.BM_LOV_SME_MAKER_DEPARTMENT IS NULL
          AND Y.BM_LOV_SME_MAKER_DEPARTMENT IS NULL
        )
        OR (
          X.BM_LOV_SME_MAKER_DEPARTMENT <> Y.BM_LOV_SME_MAKER_DEPARTMENT
        )
      )
      OR (
        (
          X.SK_CONTRACT_REF_NO IS NULL AND NOT Y.SK_CONTRACT_REF_NO IS NULL
        )
        OR (
          NOT X.SK_CONTRACT_REF_NO IS NULL AND Y.SK_CONTRACT_REF_NO IS NULL
        )
        OR (
          X.SK_CONTRACT_REF_NO <> Y.SK_CONTRACT_REF_NO
        )
      )
      OR (
        (
          X.SK_FIELD_VAL_AUDI_CUST IS NULL AND NOT Y.SK_FIELD_VAL_AUDI_CUST IS NULL
        )
        OR (
          NOT X.SK_FIELD_VAL_AUDI_CUST IS NULL AND Y.SK_FIELD_VAL_AUDI_CUST IS NULL
        )
        OR (
          X.SK_FIELD_VAL_AUDI_CUST <> Y.SK_FIELD_VAL_AUDI_CUST
        )
      )
      OR (
        (
          X.SK_FIELD_VAL_DEPOSITOR IS NULL AND NOT Y.SK_FIELD_VAL_DEPOSITOR IS NULL
        )
        OR (
          NOT X.SK_FIELD_VAL_DEPOSITOR IS NULL AND Y.SK_FIELD_VAL_DEPOSITOR IS NULL
        )
        OR (
          X.SK_FIELD_VAL_DEPOSITOR <> Y.SK_FIELD_VAL_DEPOSITOR
        )
      )
      OR (
        (
          X.SK_PRODUCT_CODE IS NULL AND NOT Y.SK_PRODUCT_CODE IS NULL
        )
        OR (
          NOT X.SK_PRODUCT_CODE IS NULL AND Y.SK_PRODUCT_CODE IS NULL
        )
        OR (
          X.SK_PRODUCT_CODE <> Y.SK_PRODUCT_CODE
        )
      )
      OR (
        (
          X.SK_FIELD_VAL_WALKING_CUST IS NULL AND NOT Y.SK_FIELD_VAL_WALKING_CUST IS NULL
        )
        OR (
          NOT X.SK_FIELD_VAL_WALKING_CUST IS NULL AND Y.SK_FIELD_VAL_WALKING_CUST IS NULL
        )
        OR (
          X.SK_FIELD_VAL_WALKING_CUST <> Y.SK_FIELD_VAL_WALKING_CUST
        )
      )
    )
    THEN 'UPD'
    WHEN X.CONTRACT_REF_NO IS NULL AND X.VERSION_NO IS NULL
    THEN 'DEL' /* - IF MULTIPLE PKs are there then concatenate them with AND */
  END AS OPT_FLAG
FROM DEVT_STG_FLX.VIEW_CONTRACT_UDF AS X
FULL JOIN DEVT_STG_FLX.VIEW_CONTRACT_UDF_BACKUP AS Y
  ON X.CONTRACT_REF_NO = Y.CONTRACT_REF_NO
  AND X.VERSION_NO = Y.VERSION_NO /* - IF MULTIPLE PKs are there then concatenate them with AND */
WHERE
  NOT OPT_FLAG IS NULL